
# on:
#   pull_request:
#     paths:
#       - "**"
#       - ".github/workflows/workflow_jest.yml"
# jobs:

#   coverage:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - run: npm install
#       - run: npm test 

#       - name: check
#         uses: sergavshin/gha-test-coverage-check@v1
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           min_threshold: '80'
#           report_file_path: 'coverage/lcov.info'