coverage:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2

    - run: npm install
    - run: npm run coverage

    - name: check
      uses: sergavshin/gha-test-coverage-check@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        min_threshold: '100'
        report_file_path: './coverage/lcov.info'