
name: test coverage check

on:
  push:
    branches:
      - '**'        # matches every branch
      - '!master'   # excludes master
  pull_request: {}

jobs:

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm install
      - run: npm test 

      - name: check
        uses: sergavshin/gha-test-coverage-check@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          min_threshold: '100'
          report_file_path: './coverage/lcov.info'